### ISSUE TITLE
Roof close should optionally park the mount

### ISSUE THREAD

**Issue by LuckyEddie47** [hjd1964/OCS#17]
Hi Howard,
I'd like to add an option to close a relay on a roof close command to tell the mount to park for setups where the roof doesn't clear the scope in all orientations. This would feed into, for example, an OnStep PARK_SIGNAL. When parked the mount can set the ROOF_INTERLOCK_SENSE to allow the roof to close safely.
As the mount parking time could be many seconds I think this needs to be non-blocking and it shouldn't return an error from Roof::close while in progress.
Can you suggest an appropriate approach for this?
Regards
Ed

**Comment by hjd1964** [comment]
I understand the appeal of letting the OCS be the master and OnStep the slave in this scenario as it's mission critical.

So...

OCS gets a roof.close() call (safety event, etc.)
If not parked already: OCS sends mount park signal and waits up to MOUNT_PARK_TIMEOUT seconds for the park, else roof.close() fails.
If parked already: OCS closes the roof.

I think I'd use a task at the start of the close() method.  Kick off the PARK_SIGNAL then fire up the task to watch for a successful park or time out.  Then exit without actually closing the roof.  The task can then run once a second and when you get a park success signal it call park().  Either way park success signal or timeout, kill the task.

The following is just the most basic outline showing where I'd start:

```
// Start closing the roof, returns true if successful or false otherwise (required)
bool Roof::close() {
  VF("MSG: Start park monitor task (rate 1000ms priority 7)... ");
  if (tasks.add(1000, 0, true, 7, parkedPoll, "pkPoll")) { VLF("success"); active = true; } else { VLF("FAILED!"); }
  // etc.
}
 
void parkedPoll() {
  // Check if the mount is parked
  if (roof.checkMountParked()) {
    // if it's parked kill this task (this would probably be in checkMountParked but keeping it simple here)
    tasks.setDurationComplete(tasks.getHandleByName("pkPoll"));
  }
}

```

**Comment by LuckyEddie47** [comment]
Thanks Howard, exactly what I was looking for. I'll work on a PR for this.
