### ISSUE TITLE
Add configurable delay to roof close on mains sense event

### ISSUE THREAD

**Issue by LuckyEddie47** [hjd1964/OCS#32]
Hi Howard,
I'm going to use a UPS to support the supplies for my observatory. Power loss of minutes/hours is thankfully rare in our area but "brown-outs" of one-few seconds are more common.
I'd like to add a configurable delay to the STAT_MAINS_SENSE check in Safety::isSafe to avoid an immediate safety shutdown in this brown-out condition (essentially a long debounce).
As this potentially impacts equipment safety I wanted to check if you agree with this approach?

**Comment by hjd1964** [comment]
The Safety.cpp code is a little difficult to wrap my mind around, looks like it'd work though.  Perhaps this would be easier to understand and pretty sure it's correct as well...

```
if (sense.isOn(STAT_MAINS_SENSE)) {
  delayForMains = 0;
} else {
  if (delayForMains < STAT_MAINS_SAFETY_DELAY) delayForMains++; else safe = false;
}

```

**Comment by hjd1964** [comment]
In StatusTile.cpp I seem to have never refactored that function into existence.

I'd either add the function (and use it for the Ajax refreshing) or drop in the correct code there as just deleting it causes whatever string happens to be in temp1 to be printed out on the first page load:

`if (sense.isOn(STAT_MAINS_SENSE)) strcpy(temp1, "GOOD"); else strcpy(temp1, "OUT");
`

**Comment by LuckyEddie47** [comment]
Cleared by #33
