### ISSUE TITLE
Software watchdog not working

### ISSUE THREAD

**Issue by LuckyEddie47** [hjd1964/OCS#6]
Using current master on OCS4 (Teensy 4.1) HW.

Came in this morning to find that my OCS had crashed - Teensy locked up with activity light permanently on.
I have #define WATCHDOG   ON and #define WATCHDOG_DURING_SD  ON (although weather is disabled at the moment so I believe that shouldn't matter).

After rebooting, I tried the :SW# reset command - I got the Teensy locked but no reboot, and no "Rebooting in 8 seconds..." response.

By temporarily copying the lines directly into the :SW# command handler in Observatory.command.cpp I've confirmed that the SCB_AIRCR = 0x05FA0004; \  asm volatile ("dsb"); does the reset correctly so I think the issue is with the watchdog function itself.

Secondarily I think the current implementation of the infinite loop in the :SW# command handler blocks the return of the command reply.

**Comment by hjd1964** [comment]
Was a hardware timer assigned? DEBUG VERBOSE will tell you.  Seems like the code should work.

Secondarily, if you'd like more refined behavior feel free to improve on the design.

**Comment by hjd1964** [comment]
Secondarily, if you'd like more refined behavior feel free to improve on the design.

Guess a task that fires after a 1 second wait (so the command response gets sent) would do it...

have a function it calls:
void lockup() { while (true) {}; }

and kick off the task in the :SW# command:
tasks.add(1000, 0, false, 7, lockup, "lockup");

For the lockup... that's odd as my builds have been very stable.  Perhaps disable most features, test for stability, then start adding back until something breaks.
